#!/usr/bin/env bash
# extract_ddl.sh — Extract full DDL (tables + procedures/functions) for all
# QuantDB project schemas: refdata, bt, trade, core_admin, inst.
#
# Uses pure psql queries (no pg_dump) — compatible regardless of client/server
# version mismatch.
#
# Produces a directory tree that mirrors db/liquidbase/:
#   <output_dir>/
#     <schema>/
#       tables/<TABLE_NAME>.sql    — one file per table
#       procedures/<PROC_NAME>.sql — one file per procedure/function
#
# Usage (run from project root):
#   source .env
#   bash .github/skills/extractddl/extract_ddl.sh [output_dir]
#
# output_dir defaults to db/syncddl
#
# Prerequisites:
#   - psql must be on PATH
#   - SSM port-forward active on localhost:5433
#   - .env sourced (sets QUANTDB_HOST, QUANTDB_PORT, QUANTDB_USERNAME, QUANTDB_PASSWORD)

set -euo pipefail

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
SCHEMAS=(refdata bt trade core_admin inst)
DB_NAME="quantdb"
HOST="${QUANTDB_HOST:-localhost}"
PORT="${QUANTDB_PORT:-5433}"
USER="${QUANTDB_USERNAME:-quant_admin}"
export PGPASSWORD="${QUANTDB_PASSWORD}"

OUTPUT_DIR="${1:-db/syncddl}"

PGCONN="host=${HOST} port=${PORT} dbname=${DB_NAME} user=${USER}"

# Run a query and return plain text rows (no headers, no alignment)
psql_q() {
  TERM=dumb PAGER='' psql "${PGCONN}" -A -t -c "$1"
}

# ---------------------------------------------------------------------------
# Type normalization: map catalog type names to project conventions
# ---------------------------------------------------------------------------
normalize_types() {
  sed \
    -e 's/timestamp with time zone/TIMESTAMPTZ/g' \
    -e 's/character varying/VARCHAR/g' \
    -e "s/character(1)/CHAR(1)/g" \
    -e 's/\binteger\b/INTEGER/g' \
    -e 's/\bbigint\b/BIGINT/g' \
    -e 's/\bsmallint\b/SMALLINT/g' \
    -e 's/\bboolean\b/BOOLEAN/g' \
    -e 's/\bnumeric\b/NUMERIC/g' \
    -e 's/\btext\b/TEXT/g' \
    -e 's/\breal\b/REAL/g'
}

# ---------------------------------------------------------------------------
# Build CREATE TABLE DDL from catalog (no pg_dump needed)
# Normalizations applied:
#   - Uppercase schema, table, column names
#   - GENERATED ALWAYS/BY DEFAULT AS IDENTITY for identity columns
#   - NOT NULL suppressed for identity columns (identity implies it)
#   - Type aliases mapped to project conventions (via normalize_types)
#   - Unique indexes skipped if already expressed as UNIQUE constraint
# ---------------------------------------------------------------------------
table_ddl() {
  local schema="$1" table="$2"
  psql_q "
SELECT
  'CREATE TABLE ' || upper('${schema}') || '.' || upper('${table}') || E' (\n'
  || string_agg(
       '    ' || upper(a.attname)
       || ' ' || CASE
           WHEN a.attidentity = 'a' THEN 'INTEGER GENERATED ALWAYS AS IDENTITY'
           WHEN a.attidentity = 'd' THEN 'INTEGER GENERATED BY DEFAULT AS IDENTITY'
           ELSE pg_catalog.format_type(a.atttypid, a.atttypmod)
         END
       || COALESCE(
            CASE WHEN a.attidentity = '' THEN
              COALESCE(' DEFAULT ' || pg_get_expr(d.adbin, d.adrelid), '')
            ELSE '' END,
            ''
          )
       || CASE WHEN a.attnotnull AND a.attidentity = '' THEN ' NOT NULL' ELSE '' END,
       E',\n'
       ORDER BY a.attnum
     )
  || COALESCE(
       E',\n' || (
         SELECT string_agg('    ' || pg_get_constraintdef(con.oid), E',\n' ORDER BY con.contype, con.conname)
         FROM pg_constraint con
         WHERE con.conrelid = c.oid
       ),
       ''
     )
  || E'\n);\n'
  || COALESCE(
       E'\n' || (
         SELECT string_agg(pg_get_indexdef(i.indexrelid) || ';', E'\n' ORDER BY ic.relname)
         FROM pg_index i
         JOIN pg_class ic ON ic.oid = i.indexrelid
         WHERE i.indrelid = c.oid
           AND NOT i.indisprimary
           AND NOT i.indisunique
       ),
       ''
     )
FROM pg_attribute a
JOIN pg_class c ON c.oid = a.attrelid
JOIN pg_namespace n ON n.oid = c.relnamespace
LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
WHERE n.nspname = '${schema}'
  AND c.relname = '${table}'
  AND a.attnum > 0
  AND NOT a.attisdropped
GROUP BY c.oid;
" | normalize_types
}

# ---------------------------------------------------------------------------
# Per-schema extraction
# ---------------------------------------------------------------------------
for SCHEMA in "${SCHEMAS[@]}"; do
  TABLES_DIR="${OUTPUT_DIR}/${SCHEMA}/tables"
  PROCS_DIR="${OUTPUT_DIR}/${SCHEMA}/procedures"
  mkdir -p "${TABLES_DIR}" "${PROCS_DIR}"

  # ---- Tables ----
  echo "[${SCHEMA}] Extracting tables..."
  while IFS= read -r TABLE; do
    [[ -z "${TABLE}" ]] && continue
    OUTFILE="${TABLES_DIR}/${TABLE^^}.sql"
    table_ddl "${SCHEMA}" "${TABLE}" > "${OUTFILE}"
    echo "  → ${OUTFILE}"
  done < <(psql_q "
    SELECT tablename FROM pg_tables
    WHERE schemaname = '${SCHEMA}'
      AND tablename NOT IN ('databasechangelog','databasechangeloglock')
    ORDER BY tablename
  ")

  # ---- Procedures / Functions ----
  echo "[${SCHEMA}] Extracting procedures/functions..."
  while IFS= read -r ROUTINE; do
    [[ -z "${ROUTINE}" ]] && continue
    OUTFILE="${PROCS_DIR}/${ROUTINE^^}.sql"
    psql_q "
      SELECT pg_get_functiondef(p.oid) || ';'
      FROM pg_proc p
      JOIN pg_namespace n ON n.oid = p.pronamespace
      WHERE n.nspname = '${SCHEMA}' AND p.proname = '${ROUTINE}'
      LIMIT 1
    " > "${OUTFILE}"
    echo "  → ${OUTFILE}"
  done < <(psql_q "
    SELECT p.proname FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = '${SCHEMA}' AND p.prokind IN ('p','f')
    ORDER BY p.proname
  ")
done

echo ""
echo "Extraction complete → ${OUTPUT_DIR}/"
