-- TRADE.DEPLOYMENT_PERFORMANCE — one strategy bar of live vs backtest return.
--
-- Soft-versioned. A recompute that changes a value inserts the next VID and
-- flips IS_CURRENT_IND. An unchanged recompute is a no-op inside
-- SP_INS_DEPLOYMENT_PERFORMANCE. One current row per
-- (DEPLOYMENT_ID, TM_INTERVAL_ID, BAR_TIMESTAMP).
--
-- LIVE_RETURN is the sum of the position, fill-gap, and fee components.
-- LIVE_FEE_RETURN and LIVE_RETURN stay null when a non-zero fee has no
-- quote amount. BACKTEST_RETURN is the Performance replay pnl for this bar.
-- Audit is USER_ID and CREATED_AT. No UPDATED_AT.
CREATE TABLE TRADE.DEPLOYMENT_PERFORMANCE (
    DEPLOYMENT_PERFORMANCE_ID   UUID NOT NULL,
    DEPLOYMENT_PERFORMANCE_VID  INTEGER NOT NULL,
    DEPLOYMENT_ID               UUID NOT NULL,
    DEPLOYMENT_VID              INTEGER NOT NULL,
    INTENT_ID                   UUID,
    TM_INTERVAL_ID              INTEGER NOT NULL,
    BAR_TIMESTAMP               TIMESTAMPTZ NOT NULL,
    IS_MANAGED_IND              CHAR(1) NOT NULL,
    TARGET_POSITION             NUMERIC,
    BACKTEST_POSITION           NUMERIC,
    UNIT_NOTIONAL_AMT           NUMERIC,
    LIVE_RETURN                 NUMERIC,
    LIVE_FILL_GAP_RETURN        NUMERIC,
    LIVE_FEE_RETURN             NUMERIC,
    BACKTEST_RETURN             NUMERIC,
    IS_CURRENT_IND              CHAR(1) NOT NULL,
    USER_ID                     TEXT NOT NULL,
    CREATED_AT                  TIMESTAMPTZ NOT NULL,

    PRIMARY KEY (DEPLOYMENT_PERFORMANCE_ID, DEPLOYMENT_PERFORMANCE_VID)
);

CREATE UNIQUE INDEX UX_DEPLOYMENT_PERFORMANCE_CURRENT
    ON TRADE.DEPLOYMENT_PERFORMANCE (DEPLOYMENT_PERFORMANCE_ID)
    WHERE IS_CURRENT_IND = 'Y';

CREATE UNIQUE INDEX UX_DEPLOYMENT_PERFORMANCE_BAR
    ON TRADE.DEPLOYMENT_PERFORMANCE (DEPLOYMENT_ID, TM_INTERVAL_ID, BAR_TIMESTAMP)
    WHERE IS_CURRENT_IND = 'Y';

CREATE INDEX IX_DEPLOYMENT_PERFORMANCE_DEPLOYMENT_BAR
    ON TRADE.DEPLOYMENT_PERFORMANCE (DEPLOYMENT_ID, BAR_TIMESTAMP DESC)
    WHERE IS_CURRENT_IND = 'Y';
