-- TRADE.DEPLOYMENT_SCHEDULE_STATUS — scheduler state per deployment (separate from
-- EXECUTION_EVENT diary). Soft-versioned via DEPLOYMENT_SCHEDULE_VID + IS_CURRENT_IND.
--
-- SCHEDULED_TS = when the next apply tick is due (written on create / tick advance).
-- STATUS drives poller eligibility (PENDING only). CREATED_AT is audit insert time.
-- STATUS values (application-enforced): PENDING | SUCCESS | FAILED
CREATE TABLE TRADE.DEPLOYMENT_SCHEDULE_STATUS (
    DEPLOYMENT_SCHEDULE_ID   UUID NOT NULL,
    DEPLOYMENT_SCHEDULE_VID  INTEGER NOT NULL,
    DEPLOYMENT_ID            UUID NOT NULL,
    DEPLOYMENT_VID           INTEGER NOT NULL,
    STATUS                   TEXT NOT NULL,
    SCHEDULED_TS             TIMESTAMPTZ NOT NULL,
    IS_CURRENT_IND           CHAR(1) NOT NULL,
    USER_ID                  TEXT NOT NULL,
    CREATED_AT               TIMESTAMPTZ NOT NULL,

    PRIMARY KEY (DEPLOYMENT_SCHEDULE_ID, DEPLOYMENT_SCHEDULE_VID)
);

CREATE UNIQUE INDEX UX_DEPLOYMENT_SCHEDULE_STATUS_CURRENT
    ON TRADE.DEPLOYMENT_SCHEDULE_STATUS (DEPLOYMENT_SCHEDULE_ID)
    WHERE IS_CURRENT_IND = 'Y';

CREATE INDEX IX_DEPLOYMENT_SCHEDULE_STATUS_DEPLOYMENT
    ON TRADE.DEPLOYMENT_SCHEDULE_STATUS (DEPLOYMENT_ID)
    WHERE IS_CURRENT_IND = 'Y';

CREATE INDEX IX_DEPLOYMENT_SCHEDULE_STATUS_DUE
    ON TRADE.DEPLOYMENT_SCHEDULE_STATUS (SCHEDULED_TS)
    WHERE STATUS = 'PENDING'
      AND IS_CURRENT_IND = 'Y';
