CREATE TABLE TRADE.LOG (
    LOG_ID        INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEPLOYMENT_ID UUID NOT NULL,
    TIMESTAMP     TIMESTAMPTZ,
    SIGNAL_VALUE  NUMERIC,
    ACTION        TEXT,
    QTY           INTEGER,
    ORDER_ID      TEXT,
    SUCCESS       CHAR(1),
    MESSAGE       TEXT,
    USER_ID       TEXT,
    CREATED_AT    TIMESTAMPTZ
);
