CREATE TABLE TRADE.TRANSACTION (
    TRANS_ID       UUID PRIMARY KEY,
    APP_ID         INTEGER,
    ORDER_STATE_ID INTEGER,
    TRANS_STATE_ID INTEGER,
    SYMBOL         TEXT NOT NULL,
    BUY_SELL_CD    TEXT NOT NULL,
    TRANS_CCY_CD   TEXT NOT NULL,
    QUANTITY       NUMERIC NOT NULL,
    PRICE          NUMERIC NOT NULL,
    NOTIONAL_AMT   NUMERIC,
    FEE_AMT        NUMERIC,
    CREATED_AT     TIMESTAMPTZ
);
