import { sql, callProc, type SpResult } from "../db/client";

// read access to database

export interface QueueRow {
  queue_id: string;
  queue_vid: number;
  strategy_id: string;
  strategy_vid: number;
  queue_status_id: number;
  queue_status: string;
  priority: number;
  error_text: string | null;
  user_id: string;
  transact_from_ts: Date;
}

export interface TerminalRow {
  queue_id: string;
  strategy_id: string;
  strategy_vid: number;
  strategy_nm: string | null;
  strat_current_ind: string;
  transact_from_ts: Date;
  queue_status: string;
  priority: number;
  user_id: string;
  config_json: unknown;
  error_text: string | null;
}

export async function queryQueue(filters: {
  queueId?: string;
  strategyId?: string;
  statusId?: number;
  userId?: string;
  limit?: number;
} = {}): Promise<QueueRow[]> {
  return sql.begin(async (tx) => {
    const out = await callProc<SpResult & { out_result: string }>(
      tx, "bt.sp_get_queue",
      (db) => db`
        CALL bt.sp_get_queue(
          ${filters.queueId ?? null}::uuid,
          ${filters.strategyId ?? null}::uuid,
          ${filters.statusId ?? null}::integer,
          ${filters.userId ?? null}::text,
          ${filters.limit ?? 50}::integer,
          NULL, NULL, NULL, NULL
        )
      `,
    );
    return tx.unsafe<QueueRow[]>(`FETCH ALL FROM "${out.out_result.replace(/"/g, '""')}"`);
  });
}

export async function queryTerminal(filters: {
  userId?: string;
  statusId?: number;
} = {}): Promise<TerminalRow[]> {
  return sql<TerminalRow[]>`
    SELECT * FROM bt.fn_get_queue_for_terminal(
      ${filters.userId ?? null}::text,
      ${filters.statusId ?? null}::integer
    ) LIMIT 50
  `;
}

// write access to database

export async function enqueue(params: { 
  queueId: string;        // generated by caller (uuidv4)
  strategyId: string;
  strategyVid: number;
  statusId: number;       // QUEUED — resolved from refdata cache
  priority: number;
  userId: string;
}): Promise<void> {
  await callProc(sql, "bt.sp_ins_queue", (db) => db`
    CALL bt.sp_ins_queue(
      ${params.queueId}::uuid,
      ${params.strategyId}::uuid,
      ${params.strategyVid}::integer,
      ${params.statusId}::integer,
      ${params.priority}::integer,
      ${null}::text,
      ${params.userId}::text,
      NULL, NULL, NULL
    )
  `);
}

/** Count active QUEUED rows owned by `userId` — used for the 20-job rate limit. */
export async function countQueuedForUser(
  userId: string,
  queuedStatusId: number,
): Promise<number> {
  const out = await callProc<SpResult & { out_count: number }>(
    sql, "bt.sp_get_queued_count",
    (db) => db`
      CALL bt.sp_get_queued_count(
        ${userId}::text,
        ${queuedStatusId}::integer,
        NULL, NULL, NULL, NULL
      )
    `,
  );
  return Number(out.out_count ?? 0);
}

export interface ClaimedJob {
  queue_id: string;
  strategy_id: string;
  strategy_vid: number;
  priority: number;
  user_id: string;
}

/**
 * Claim the head of the QUEUED ranking and transition it to RUNNING.
 *
 * Phase 1 (single coordinator, per docs/design/backtest-queue.md §9.4):
 * read head + write RUNNING in one transaction. Phase 2 will collapse this
 * into a single atomic `SP_CLAIM_NEXT` (needed for multi-coordinator).
 *
 * Returns `null` when the queue is empty.
 */
export async function claimNext(
  queuedStatusId: number,
  runningStatusId: number,
): Promise<ClaimedJob | null> {
  return sql.begin(async (tx) => {
    const head = await tx<TerminalRow[]>`
      SELECT * FROM bt.fn_get_queue_for_terminal(
        ${null}::text,
        ${queuedStatusId}::integer
      ) LIMIT 1
    `;
    const row = head[0];
    if (!row) return null;

    await callProc(tx, "bt.sp_ins_queue", (db) => db`
      CALL bt.sp_ins_queue(
        ${row.queue_id}::uuid,
        ${row.strategy_id}::uuid,
        ${row.strategy_vid}::integer,
        ${runningStatusId}::integer,
        ${row.priority}::integer,
        ${null}::text,
        ${row.user_id}::text,
        NULL, NULL, NULL
      )
    `);

    return {
      queue_id: row.queue_id,
      strategy_id: row.strategy_id,
      strategy_vid: row.strategy_vid,
      priority: row.priority,
      user_id: row.user_id,
    };
  });
}

