import { sql, callProc, type Sql, type SpResult } from "../db/client";

// read access to database

export interface QueueRow {
  queue_id: string;
  queue_vid: number;
  strategy_id: string;
  strategy_vid: number;
  queue_status_id: number;
  queue_status: string;
  priority: number;
  error_text: string | null;
  user_id: string;
  transact_from_ts: Date;
}

export interface TerminalRow {
  queue_id: string;
  strategy_id: string;
  strategy_vid: number;
  strategy_nm: string | null;
  strat_current_ind: string;
  transact_from_ts: Date;
  queue_status: string;
  priority: number;
  user_id: string;
  config_json: unknown;
  error_text: string | null;
}

export async function queryQueue(filters: {
  queueId?: string;
  strategyId?: string;
  statusId?: number;
  priority?: number;
  userId?: string;
  limit?: number;
} = {}): Promise<QueueRow[]> {
  return sql<QueueRow[]>`
    SELECT * FROM bt.fn_get_queue(
      ${filters.queueId ?? null}::uuid,
      ${filters.strategyId ?? null}::uuid,
      ${filters.statusId ?? null}::integer,
      ${filters.priority ?? null}::integer,
      ${filters.userId ?? null}::text,
      ${filters.limit ?? 50}::integer
    )
  `;
}

export async function queryTerminal(filters: {
  userId?: string;
  statusId?: number;
  limit?: number;
} = {}): Promise<TerminalRow[]> {
  return sql<TerminalRow[]>`
    SELECT * FROM bt.fn_get_queue_for_terminal(
      ${filters.userId ?? null}::text,
      ${filters.statusId ?? null}::integer,
      ${filters.limit ?? 50}::integer
    )
  `;
}

// write access to database

export async function enqueue(params: { 
  queueId: string;        // generated by caller (uuidv4)
  strategyId: string;
  strategyVid: number;
  statusId: number;       // QUEUED — resolved from refdata cache
  priority: number;
  userId: string;
}): Promise<void> {
  await callProc(sql, "bt.sp_ins_queue", (db) => db`
    CALL bt.sp_ins_queue(
      ${params.queueId}::uuid,
      ${params.strategyId}::uuid,
      ${params.strategyVid}::integer,
      ${params.statusId}::integer,
      ${params.priority}::integer,
      ${null}::text,
      ${params.userId}::text,
      NULL, NULL, NULL
    )
  `);
}
  

