CREATE OR REPLACE PROCEDURE BT.INSERT_API_REQUEST(
    IN  IN_API_REQ_ID       UUID,
    IN  IN_APP_ID           INTEGER,
    IN  IN_TM_INTERVAL_ID   INTEGER,
    IN  IN_SYMBOL           TEXT,
    IN  IN_FULL_RANGE_START TIMESTAMPTZ,
    IN  IN_FULL_RANGE_END   TIMESTAMPTZ,
    IN  IN_IS_CURRENT_IND   CHAR(1),
    IN  IN_USER_ID          TEXT,
    IN  IN_CREATED_AT       TIMESTAMPTZ,
    OUT OUT_SQLSTATE        TEXT,
    OUT OUT_SQLERRMC        TEXT
)
LANGUAGE plpgsql
AS $$
BEGIN
    OUT_SQLSTATE := '00000';
    OUT_SQLERRMC := NULL;

    INSERT INTO BT.API_REQUEST (
        API_REQ_ID, APP_ID, TM_INTERVAL_ID, SYMBOL,
        FULL_RANGE_START, FULL_RANGE_END, IS_CURRENT_IND,
        USER_ID, CREATED_AT
    ) VALUES (
        IN_API_REQ_ID, IN_APP_ID, IN_TM_INTERVAL_ID, IN_SYMBOL,
        IN_FULL_RANGE_START, IN_FULL_RANGE_END, IN_IS_CURRENT_IND,
        IN_USER_ID, IN_CREATED_AT
    );

EXCEPTION
    WHEN OTHERS THEN
        GET STACKED DIAGNOSTICS
            OUT_SQLSTATE = RETURNED_SQLSTATE,
            OUT_SQLERRMC = MESSAGE_TEXT;
END;
$$;
