CREATE OR REPLACE PROCEDURE BT.INSERT_STRATEGY(
    IN  IN_STRATEGY_ID    UUID,
    IN  IN_NAME           TEXT,
    IN  IN_VERSION        INTEGER,
    IN  IN_TICKER         TEXT,
    IN  IN_CONJUNCTION    TEXT,
    IN  IN_TRADING_PERIOD INTEGER,
    IN  IN_CONFIG_JSON    JSONB,
    IN  IN_USER_ID        TEXT,
    IN  IN_CREATED_AT     TIMESTAMPTZ,
    IN  IN_UPDATED_AT     TIMESTAMPTZ,
    IN  IN_IS_CURRENT_IND CHAR(1),
    OUT OUT_SQLSTATE      TEXT,
    OUT OUT_SQLERRMC      TEXT
)
LANGUAGE plpgsql
AS $$
BEGIN
    OUT_SQLSTATE := '00000';
    OUT_SQLERRMC := NULL;

    INSERT INTO BT.STRATEGY (
        STRATEGY_ID, NAME, VERSION, TICKER, CONJUNCTION,
        TRADING_PERIOD, CONFIG_JSON, USER_ID, CREATED_AT,
        UPDATED_AT, IS_CURRENT_IND
    ) VALUES (
        IN_STRATEGY_ID, IN_NAME, IN_VERSION, IN_TICKER, IN_CONJUNCTION,
        IN_TRADING_PERIOD, IN_CONFIG_JSON, IN_USER_ID, IN_CREATED_AT,
        IN_UPDATED_AT, IN_IS_CURRENT_IND
    );

EXCEPTION
    WHEN OTHERS THEN
        GET STACKED DIAGNOSTICS
            OUT_SQLSTATE = RETURNED_SQLSTATE,
            OUT_SQLERRMC = MESSAGE_TEXT;
END;
$$;
