CREATE OR REPLACE PROCEDURE BT.INSERT_API_REQUEST_PAYLOAD(
    IN  IN_API_REQ_ID     UUID,
    IN  IN_API_REQ_VID    INTEGER,
    IN  IN_RANGE_START_TS TIMESTAMPTZ,
    IN  IN_RANGE_END_TS   TIMESTAMPTZ,
    IN  IN_PAYLOAD        JSONB,
    IN  IN_USER_ID        TEXT,
    IN  IN_CREATED_AT     TIMESTAMPTZ,
    OUT OUT_SQLSTATE      TEXT,
    OUT OUT_SQLERRMC      TEXT
)
LANGUAGE plpgsql
AS $$
BEGIN
    OUT_SQLSTATE := '00000';
    OUT_SQLERRMC := NULL;

    INSERT INTO BT.API_REQUEST_PAYLOAD (
        API_REQ_ID, API_REQ_VID, RANGE_START_TS, RANGE_END_TS,
        PAYLOAD, USER_ID, CREATED_AT
    ) VALUES (
        IN_API_REQ_ID, IN_API_REQ_VID, IN_RANGE_START_TS, IN_RANGE_END_TS,
        IN_PAYLOAD, IN_USER_ID, IN_CREATED_AT
    );

EXCEPTION
    WHEN OTHERS THEN
        GET STACKED DIAGNOSTICS
            OUT_SQLSTATE = RETURNED_SQLSTATE,
            OUT_SQLERRMC = MESSAGE_TEXT;
END;
$$;
