CREATE OR REPLACE PROCEDURE BT.SP_INS_API_REQUEST_PAYLOAD(
    IN  IN_API_REQ_ID     UUID,
    IN  IN_API_REQ_VID    INTEGER,
    IN  IN_RANGE_START_TS TIMESTAMPTZ,
    IN  IN_RANGE_END_TS   TIMESTAMPTZ,
    IN  IN_PAYLOAD        JSONB,
    IN  IN_USER_ID        TEXT,
    OUT OUT_SQLSTATE      TEXT,
    OUT OUT_SQLMSG        TEXT,
    OUT OUT_SQLERRMC      TEXT
)
LANGUAGE plpgsql
AS $$
DECLARE
    V_START_TS   TIMESTAMPTZ := CURRENT_TIMESTAMP;
    V_OTHER_TEXT TEXT;
    V_LOG_STATE  TEXT;
    V_LOG_MSG    TEXT;
BEGIN
    OUT_SQLSTATE := '00000';
    OUT_SQLMSG   := '0';
    OUT_SQLERRMC := 'Stored Procedure completed successfully';

    V_OTHER_TEXT := 'IN_API_REQ_ID=' || COALESCE(IN_API_REQ_ID::TEXT, '')
                 || ', IN_API_REQ_VID=' || COALESCE(IN_API_REQ_VID::TEXT, '');

    OUT_SQLMSG := '10';
    INSERT INTO BT.API_REQUEST_PAYLOAD (
        API_REQ_ID,
        API_REQ_VID,
        RANGE_START_TS,
        RANGE_END_TS,
        PAYLOAD,
        USER_ID,
        CREATED_AT
    ) VALUES (
        IN_API_REQ_ID,
        IN_API_REQ_VID,
        IN_RANGE_START_TS,
        IN_RANGE_END_TS,
        IN_PAYLOAD,
        IN_USER_ID,
        NOW()
    );

    OUT_SQLMSG := '20';
    CALL CORE_ADMIN.CORE_INS_LOG_PROC('BT', 'SP_INS_API_REQUEST_PAYLOAD', V_START_TS, NULL, V_OTHER_TEXT, IN_USER_ID, V_LOG_STATE, V_LOG_MSG);

EXCEPTION
    WHEN OTHERS THEN
        DECLARE
            V_DETAIL  TEXT;
            V_CONTEXT TEXT;
        BEGIN
            GET STACKED DIAGNOSTICS
                OUT_SQLSTATE = RETURNED_SQLSTATE,
                OUT_SQLERRMC = MESSAGE_TEXT,
                V_DETAIL     = PG_EXCEPTION_DETAIL,
                V_CONTEXT    = PG_EXCEPTION_CONTEXT;

            RAISE WARNING '[SP_INS_API_REQUEST_PAYLOAD] % (SQLSTATE: %). Detail: %. Context: %. Params: %',
                OUT_SQLERRMC, OUT_SQLSTATE, V_DETAIL, V_CONTEXT, V_OTHER_TEXT;
        END;
END;
$$;
