CREATE OR REPLACE PROCEDURE CORE_ADMIN.CORE_INS_LOG_PROC(
    IN  IN_SCHEMA_NM    TEXT,
    IN  IN_PROC_NM      TEXT,
    IN  IN_CREATED_AT   TIMESTAMPTZ,
    IN  IN_END_AT       TIMESTAMPTZ,
    IN  IN_OTHER_TEXT   TEXT,
    IN  IN_USER_ID      TEXT,
    OUT OUT_SQLSTATE    TEXT,
    OUT OUT_SQLERRMC    TEXT
)
LANGUAGE plpgsql
AS $$
DECLARE
    V_END_AT    TIMESTAMPTZ;
    V_DURATION  DOUBLE PRECISION;
BEGIN
    OUT_SQLSTATE := '00000';
    OUT_SQLERRMC := NULL;

    IF IN_END_AT IS NULL THEN
        V_END_AT := CURRENT_TIMESTAMP;
    ELSE
        V_END_AT := IN_END_AT;
    END IF;

    V_DURATION := EXTRACT(EPOCH FROM (V_END_AT - IN_CREATED_AT)) * 1000;

    INSERT INTO CORE_ADMIN.LOG_PROC_DETAIL (
        SCHEMA_NM, PROC_NM, CREATED_AT, END_AT,
        OTHER_TEXT, DURATION, USER_ID
    ) VALUES (
        IN_SCHEMA_NM, IN_PROC_NM, IN_CREATED_AT, V_END_AT,
        IN_OTHER_TEXT, V_DURATION, IN_USER_ID
    );

EXCEPTION
    WHEN OTHERS THEN
        GET STACKED DIAGNOSTICS
            OUT_SQLSTATE = RETURNED_SQLSTATE,
            OUT_SQLERRMC = MESSAGE_TEXT;
END;
$$;
