CREATE OR REPLACE PROCEDURE CORE_ADMIN.SP_INS_LOG_PROC_SUMMARY(
    IN  IN_USER_ID         TEXT    DEFAULT 'system',
    IN  IN_RETENTION_DAYS  INTEGER DEFAULT 30,
    OUT OUT_SQLSTATE       TEXT,
    OUT OUT_SQLMSG         TEXT,
    OUT OUT_SQLERRMC       TEXT,
    OUT OUT_ROWS_AFFECTED  INTEGER
)
LANGUAGE plpgsql
SET plan_cache_mode = 'force_generic_plan'
AS $$
DECLARE
    V_SINCE         DATE;
    V_PURGE_BEFORE  TIMESTAMPTZ;
    V_PURGED        INTEGER;
BEGIN
    OUT_SQLSTATE := '00000';
    OUT_SQLMSG   := 'SUCCESS';
    OUT_SQLERRMC := NULL;

    -- 1. Summarize: aggregate unsummarized complete days
    SELECT COALESCE(MAX(SUMMARY_DT) + 1, '1970-01-01'::DATE)
      INTO V_SINCE
      FROM CORE_ADMIN.LOG_PROC_SUMMARY;

    INSERT INTO CORE_ADMIN.LOG_PROC_SUMMARY (
        SUMMARY_DT, SCHEMA_NM, PROC_NM,
        CALL_COUNT, AVG_DURATION_MS, MAX_DURATION_MS, MIN_DURATION_MS,
        CREATED_AT, USER_ID
    )
    SELECT
        DATE(CREATED_AT),
        SCHEMA_NM,
        PROC_NM,
        COUNT(*),
        AVG(DURATION),
        MAX(DURATION),
        MIN(DURATION),
        NOW(),
        IN_USER_ID
    FROM CORE_ADMIN.LOG_PROC_DETAIL
    WHERE CREATED_AT >= V_SINCE::TIMESTAMPTZ
      AND CREATED_AT <  CURRENT_DATE::TIMESTAMPTZ
    GROUP BY DATE(CREATED_AT), SCHEMA_NM, PROC_NM;

    GET DIAGNOSTICS OUT_ROWS_AFFECTED = ROW_COUNT;

    -- 2. Purge: remove detail rows older than retention window.
    --    Rows within the window are kept for ad-hoc debugging.
    V_PURGE_BEFORE := (CURRENT_DATE - IN_RETENTION_DAYS)::TIMESTAMPTZ;

    DELETE FROM CORE_ADMIN.LOG_PROC_DETAIL
     WHERE CREATED_AT < V_PURGE_BEFORE;

    GET DIAGNOSTICS V_PURGED = ROW_COUNT;

    IF V_PURGED > 0 THEN
        RAISE NOTICE 'SP_INS_LOG_PROC_SUMMARY: purged % detail rows older than %',
                      V_PURGED, V_PURGE_BEFORE;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        GET STACKED DIAGNOSTICS
            OUT_SQLSTATE = RETURNED_SQLSTATE,
            OUT_SQLERRMC = MESSAGE_TEXT;
        OUT_SQLMSG := 'ERROR';
END;
$$;
