CREATE OR REPLACE PROCEDURE CORE_ADMIN.SP_UPD_APP_USER_ACTIVE(
    IN  IN_USERNAME       TEXT,
    IN  IN_IS_ACTIVE_IND  CHAR,
    IN  IN_USER_ID        TEXT,
    OUT OUT_SQLSTATE      TEXT,
    OUT OUT_SQLMSG        TEXT,
    OUT OUT_SQLERRMC      TEXT
)
LANGUAGE plpgsql
AS $$
DECLARE
    V_START_TS   TIMESTAMPTZ := CURRENT_TIMESTAMP;
    V_OTHER_TEXT TEXT;
    V_LOG_STATE  TEXT;
    V_LOG_MSG    TEXT;
BEGIN
    OUT_SQLSTATE := '00000';
    OUT_SQLMSG   := '0';
    OUT_SQLERRMC := 'Stored Procedure completed successfully';

    V_OTHER_TEXT := 'IN_USERNAME=' || COALESCE(IN_USERNAME, '')
                 || ', IN_IS_ACTIVE_IND=' || COALESCE(IN_IS_ACTIVE_IND, '');

    OUT_SQLMSG := '10';
    UPDATE CORE_ADMIN.APP_USER
       SET IS_ACTIVE_IND = IN_IS_ACTIVE_IND,
           SESSION_GEN   = SESSION_GEN + 1,
           UPDATED_AT    = NOW()
     WHERE USERNAME = IN_USERNAME;

    OUT_SQLMSG := '20';
    CALL CORE_ADMIN.CORE_INS_LOG_PROC('CORE_ADMIN', 'SP_UPD_APP_USER_ACTIVE', V_START_TS, NULL, V_OTHER_TEXT, IN_USER_ID, V_LOG_STATE, V_LOG_MSG);

EXCEPTION
    WHEN OTHERS THEN
        DECLARE
            V_DETAIL  TEXT;
            V_CONTEXT TEXT;
        BEGIN
            GET STACKED DIAGNOSTICS
                OUT_SQLSTATE = RETURNED_SQLSTATE,
                OUT_SQLERRMC = MESSAGE_TEXT,
                V_DETAIL     = PG_EXCEPTION_DETAIL,
                V_CONTEXT    = PG_EXCEPTION_CONTEXT;

            RAISE WARNING '[SP_UPD_APP_USER_ACTIVE] % (SQLSTATE: %). Detail: %. Context: %. Params: %',
                OUT_SQLERRMC, OUT_SQLSTATE, V_DETAIL, V_CONTEXT, V_OTHER_TEXT;
        END;
END;
$$;
