CREATE OR REPLACE PROCEDURE INST.SP_INS_PRODUCT_GRP_MEMBER(
    IN  IN_PRODUCT_GRP_ID  INTEGER,
    IN  IN_PRODUCT_ID      INTEGER,
    IN  IN_IS_ACTIVE_IND   CHAR(1),
    IN  IN_USER_ID         TEXT,
    OUT OUT_SQLSTATE        TEXT,
    OUT OUT_SQLMSG          TEXT,
    OUT OUT_SQLERRMC        TEXT
)
LANGUAGE plpgsql
AS $$
DECLARE
    V_START_TS   TIMESTAMPTZ := CURRENT_TIMESTAMP;
    V_OTHER_TEXT TEXT;
    V_LOG_STATE  TEXT;
    V_LOG_MSG    TEXT;
BEGIN
    OUT_SQLSTATE := '00000';
    OUT_SQLMSG   := '0';
    OUT_SQLERRMC := 'Stored Procedure completed successfully';

    V_OTHER_TEXT := 'IN_PRODUCT_GRP_ID=' || COALESCE(IN_PRODUCT_GRP_ID::TEXT, '')
                 || ', IN_PRODUCT_ID=' || COALESCE(IN_PRODUCT_ID::TEXT, '');

    -- Step 10: Insert membership row
    OUT_SQLMSG := '10';
    INSERT INTO INST.PRODUCT_GRP_MEMBER (
        PRODUCT_GRP_ID,
        PRODUCT_ID,
        IS_ACTIVE_IND,
        USER_ID,
        CREATED_AT
    ) VALUES (
        IN_PRODUCT_GRP_ID,
        IN_PRODUCT_ID,
        IN_IS_ACTIVE_IND,
        IN_USER_ID,
        NOW()
    );

    OUT_SQLMSG := '20';
    CALL CORE_ADMIN.CORE_INS_LOG_PROC('INST', 'SP_INS_PRODUCT_GRP_MEMBER', V_START_TS, NULL, V_OTHER_TEXT, IN_USER_ID, V_LOG_STATE, V_LOG_MSG);

EXCEPTION
    WHEN OTHERS THEN
        DECLARE
            V_DETAIL  TEXT;
            V_CONTEXT TEXT;
        BEGIN
            GET STACKED DIAGNOSTICS
                OUT_SQLSTATE = RETURNED_SQLSTATE,
                OUT_SQLERRMC = MESSAGE_TEXT,
                V_DETAIL     = PG_EXCEPTION_DETAIL,
                V_CONTEXT    = PG_EXCEPTION_CONTEXT;

            RAISE WARNING '[SP_INS_PRODUCT_GRP_MEMBER] % (SQLSTATE: %). Detail: %. Context: %. Params: %',
                OUT_SQLERRMC, OUT_SQLSTATE, V_DETAIL, V_CONTEXT, V_OTHER_TEXT;
        END;
END;
$$;
