-- Write one strategy performance bar.
--
-- Natural key: (DEPLOYMENT_ID, TM_INTERVAL_ID, BAR_TIMESTAMP).
-- A current row whose value columns are unchanged (IS NOT DISTINCT FROM)
-- is a no-op. A change reuses that row's id, inserts the next VID, and
-- flips the previous current row to N. A new bar uses IN_DEPLOYMENT_PERFORMANCE_ID
-- and VID 1.
--
-- VID and IS_CURRENT_IND are computed here. CREATED_AT is NOW().
-- Validation lives in Python (TradeRepo).
CREATE OR REPLACE PROCEDURE TRADE.SP_INS_DEPLOYMENT_PERFORMANCE(
    IN  IN_DEPLOYMENT_PERFORMANCE_ID  UUID,
    IN  IN_DEPLOYMENT_ID               UUID,
    IN  IN_DEPLOYMENT_VID              INTEGER,
    IN  IN_INTENT_ID                   UUID,
    IN  IN_TM_INTERVAL_ID              INTEGER,
    IN  IN_BAR_TIMESTAMP               TIMESTAMPTZ,
    IN  IN_IS_MANAGED_IND              CHAR(1),
    IN  IN_TARGET_POSITION             NUMERIC,
    IN  IN_BACKTEST_POSITION           NUMERIC,
    IN  IN_UNIT_NOTIONAL_AMT           NUMERIC,
    IN  IN_LIVE_RETURN                 NUMERIC,
    IN  IN_LIVE_FILL_GAP_RETURN        NUMERIC,
    IN  IN_LIVE_FEE_RETURN             NUMERIC,
    IN  IN_BACKTEST_RETURN             NUMERIC,
    IN  IN_USER_ID                     TEXT,
    OUT OUT_SQLSTATE                   TEXT,
    OUT OUT_SQLMSG                     TEXT,
    OUT OUT_SQLERRMC                   TEXT
)
LANGUAGE plpgsql
SET plan_cache_mode = 'force_generic_plan'
AS $$
DECLARE
    V_LOG_START  TIMESTAMPTZ := clock_timestamp();
    V_OTHER_TEXT TEXT;
    V_LOG_STATE  TEXT;
    V_LOG_MSG    TEXT;
    V_ROW        TRADE.DEPLOYMENT_PERFORMANCE%ROWTYPE;
    V_ID         UUID;
    V_VID        INTEGER;
BEGIN
    OUT_SQLSTATE := '00000';
    OUT_SQLMSG   := '0';
    OUT_SQLERRMC := 'Stored Procedure completed successfully';

    V_OTHER_TEXT := 'IN_DEPLOYMENT_ID=' || COALESCE(IN_DEPLOYMENT_ID::TEXT, '')
                 || ', IN_TM_INTERVAL_ID=' || COALESCE(IN_TM_INTERVAL_ID::TEXT, '')
                 || ', IN_BAR_TIMESTAMP=' || COALESCE(IN_BAR_TIMESTAMP::TEXT, '');

    OUT_SQLMSG := '10';
    SELECT *
      INTO V_ROW
      FROM TRADE.DEPLOYMENT_PERFORMANCE
     WHERE DEPLOYMENT_ID = IN_DEPLOYMENT_ID
       AND TM_INTERVAL_ID = IN_TM_INTERVAL_ID
       AND BAR_TIMESTAMP = IN_BAR_TIMESTAMP
       AND IS_CURRENT_IND = 'Y';

    IF FOUND
       AND V_ROW.DEPLOYMENT_VID       IS NOT DISTINCT FROM IN_DEPLOYMENT_VID
       AND V_ROW.INTENT_ID            IS NOT DISTINCT FROM IN_INTENT_ID
       AND V_ROW.IS_MANAGED_IND       IS NOT DISTINCT FROM IN_IS_MANAGED_IND
       AND V_ROW.TARGET_POSITION      IS NOT DISTINCT FROM IN_TARGET_POSITION
       AND V_ROW.BACKTEST_POSITION    IS NOT DISTINCT FROM IN_BACKTEST_POSITION
       AND V_ROW.UNIT_NOTIONAL_AMT    IS NOT DISTINCT FROM IN_UNIT_NOTIONAL_AMT
       AND V_ROW.LIVE_RETURN          IS NOT DISTINCT FROM IN_LIVE_RETURN
       AND V_ROW.LIVE_FILL_GAP_RETURN IS NOT DISTINCT FROM IN_LIVE_FILL_GAP_RETURN
       AND V_ROW.LIVE_FEE_RETURN      IS NOT DISTINCT FROM IN_LIVE_FEE_RETURN
       AND V_ROW.BACKTEST_RETURN      IS NOT DISTINCT FROM IN_BACKTEST_RETURN
    THEN
        OUT_SQLMSG   := '15';
        OUT_SQLERRMC := 'unchanged';
        CALL CORE_ADMIN.CORE_INS_LOG_PROC(
            'TRADE', 'SP_INS_DEPLOYMENT_PERFORMANCE', V_LOG_START, NULL, V_OTHER_TEXT,
            IN_USER_ID, V_LOG_STATE, V_LOG_MSG
        );
        RETURN;
    END IF;

    OUT_SQLMSG := '20';
    IF FOUND THEN
        V_ID := V_ROW.DEPLOYMENT_PERFORMANCE_ID;
    ELSE
        V_ID := IN_DEPLOYMENT_PERFORMANCE_ID;
    END IF;

    SELECT COALESCE(MAX(DEPLOYMENT_PERFORMANCE_VID), 0) + 1
      INTO V_VID
      FROM TRADE.DEPLOYMENT_PERFORMANCE
     WHERE DEPLOYMENT_PERFORMANCE_ID = V_ID;

    UPDATE TRADE.DEPLOYMENT_PERFORMANCE
       SET IS_CURRENT_IND = 'N'
     WHERE DEPLOYMENT_PERFORMANCE_ID = V_ID
       AND IS_CURRENT_IND = 'Y';

    OUT_SQLMSG := '30';
    INSERT INTO TRADE.DEPLOYMENT_PERFORMANCE (
        DEPLOYMENT_PERFORMANCE_ID,
        DEPLOYMENT_PERFORMANCE_VID,
        DEPLOYMENT_ID,
        DEPLOYMENT_VID,
        INTENT_ID,
        TM_INTERVAL_ID,
        BAR_TIMESTAMP,
        IS_MANAGED_IND,
        TARGET_POSITION,
        BACKTEST_POSITION,
        UNIT_NOTIONAL_AMT,
        LIVE_RETURN,
        LIVE_FILL_GAP_RETURN,
        LIVE_FEE_RETURN,
        BACKTEST_RETURN,
        IS_CURRENT_IND,
        USER_ID,
        CREATED_AT
    ) VALUES (
        V_ID,
        V_VID,
        IN_DEPLOYMENT_ID,
        IN_DEPLOYMENT_VID,
        IN_INTENT_ID,
        IN_TM_INTERVAL_ID,
        IN_BAR_TIMESTAMP,
        IN_IS_MANAGED_IND,
        IN_TARGET_POSITION,
        IN_BACKTEST_POSITION,
        IN_UNIT_NOTIONAL_AMT,
        IN_LIVE_RETURN,
        IN_LIVE_FILL_GAP_RETURN,
        IN_LIVE_FEE_RETURN,
        IN_BACKTEST_RETURN,
        'Y',
        IN_USER_ID,
        NOW()
    );

    OUT_SQLMSG := '40';
    CALL CORE_ADMIN.CORE_INS_LOG_PROC(
        'TRADE', 'SP_INS_DEPLOYMENT_PERFORMANCE', V_LOG_START, NULL, V_OTHER_TEXT,
        IN_USER_ID, V_LOG_STATE, V_LOG_MSG
    );

EXCEPTION
    WHEN OTHERS THEN
        DECLARE
            V_DETAIL  TEXT;
            V_CONTEXT TEXT;
        BEGIN
            GET STACKED DIAGNOSTICS
                OUT_SQLSTATE = RETURNED_SQLSTATE,
                OUT_SQLERRMC = MESSAGE_TEXT,
                V_DETAIL     = PG_EXCEPTION_DETAIL,
                V_CONTEXT    = PG_EXCEPTION_CONTEXT;

            RAISE WARNING '[SP_INS_DEPLOYMENT_PERFORMANCE] % (SQLSTATE: %). Detail: %. Context: %. Params: %',
                OUT_SQLERRMC, OUT_SQLSTATE, V_DETAIL, V_CONTEXT, V_OTHER_TEXT;
        END;
END;
$$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'quant_app') THEN
    GRANT EXECUTE ON PROCEDURE TRADE.SP_INS_DEPLOYMENT_PERFORMANCE(
        UUID, UUID, INTEGER, UUID, INTEGER, TIMESTAMPTZ, CHAR(1),
        NUMERIC, NUMERIC, NUMERIC, NUMERIC, NUMERIC, NUMERIC, NUMERIC, TEXT,
        OUT TEXT, OUT TEXT, OUT TEXT
    ) TO quant_app;
  END IF;
END $$;
