CREATE TABLE INST.PRODUCT_GRP_MEMBER (
    PRODUCT_GRP_ID INTEGER NOT NULL,
    PRODUCT_ID INTEGER NOT NULL,
    IS_ACTIVE_IND CHAR(1),
    USER_ID TEXT,
    CREATED_AT TIMESTAMPTZ,
    PRIMARY KEY (PRODUCT_GRP_ID, PRODUCT_ID)
);
