CREATE TABLE INST.PRODUCT_GRP (
    PRODUCT_GRP_ID INTEGER GENERATED ALWAYS AS IDENTITY,
    PARENT_GRP_ID INTEGER,
    GRP_LEVEL INTEGER NOT NULL,
    GRP_NM TEXT NOT NULL,
    DISPLAY_NAME TEXT NOT NULL,
    DESCRIPTION TEXT,
    USER_ID TEXT,
    UPDATED_AT TIMESTAMPTZ,
    PRIMARY KEY (PRODUCT_GRP_ID),
    UNIQUE (GRP_NM)
);
