CREATE TABLE INST.PRODUCT (
    PRODUCT_ID INTEGER NOT NULL,
    PRODUCT_VID INTEGER NOT NULL,
    IS_CURRENT_IND CHAR(1),
    INTERNAL_CUSIP TEXT NOT NULL,
    DISPLAY_NM TEXT NOT NULL,
    ASSET_TYPE_ID INTEGER,
    EXCHANGE TEXT,
    CCY TEXT,
    DESCRIPTION TEXT,
    USER_ID TEXT,
    CREATED_AT TIMESTAMPTZ,

    PRIMARY KEY (PRODUCT_ID, PRODUCT_VID)
);

CREATE UNIQUE INDEX UQ_PRODUCT_CUSIP_CURRENT
    ON INST.PRODUCT (INTERNAL_CUSIP)
    WHERE IS_CURRENT_IND = 'Y';
