CREATE TABLE INST.PRODUCT_XREF (
    PRODUCT_XREF_ID INTEGER NOT NULL,
    PRODUCT_XREF_VID INTEGER NOT NULL,
    TRANSACT_FROM_TS TIMESTAMPTZ NOT NULL,
    TRANSACT_TO_TS TIMESTAMPTZ NOT NULL,
    PRODUCT_ID INTEGER NOT NULL,
    APP_ID INTEGER NOT NULL,
    VENDOR_SYMBOL TEXT NOT NULL,
    USER_ID TEXT,
    CREATED_AT TIMESTAMPTZ,
    PRIMARY KEY (PRODUCT_XREF_ID, PRODUCT_XREF_VID)
);

CREATE UNIQUE INDEX UQ_PRODUCT_XREF_CURRENT
    ON INST.PRODUCT_XREF (PRODUCT_ID, APP_ID)
    WHERE TRANSACT_TO_TS = TIMESTAMPTZ '9999-12-31';
