CREATE TABLE REFDATA.API_LIMIT (
    API_LIMIT_ID    INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    APP_ID          INTEGER ,
    LIMIT_TYPE      TEXT NOT NULL,
    MAX_VALUE       INTEGER NOT NULL,
    TIME_WINDOW_SEC INTEGER,
    DESCRIPTION     TEXT,
    USER_ID         TEXT,
    UPDATED_AT      TIMESTAMPTZ
);
