CREATE TABLE REFDATA.APP (
    APP_ID           INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME             TEXT NOT NULL UNIQUE,
    DISPLAY_NAME     TEXT NOT NULL,
    CLASS_NAME       TEXT NOT NULL,
    IS_EXCHANGE_IND  CHAR(1) NOT NULL,
    DESCRIPTION      TEXT,
    USER_ID          TEXT,
    UPDATED_AT       TIMESTAMPTZ
);
