CREATE TABLE REFDATA.APP (
    APP_ID       INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME         TEXT NOT NULL,
    DESCRIPTION  TEXT,
    USER_ID      TEXT,
    UPDATED_AT   TIMESTAMPTZ
);
