CREATE TABLE REFDATA.APP_METRIC (
    APP_METRIC_ID  INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    APP_ID         INTEGER NOT NULL,
    METRIC_NM      TEXT NOT NULL,
    DISPLAY_NAME   TEXT NOT NULL,
    METRIC_PATH    TEXT,
    DATA_CATEGORY  TEXT NOT NULL,
    METHOD_NAME    TEXT NOT NULL,
    DESCRIPTION    TEXT,
    USER_ID        TEXT,
    UPDATED_AT     TIMESTAMPTZ,
    UNIQUE (APP_ID, METRIC_NM)
);
