CREATE TABLE REFDATA.INDICATOR (
    INDICATOR_ID   INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME           TEXT NOT NULL UNIQUE,
    DISPLAY_NAME   TEXT NOT NULL,
    METHOD_NAME    TEXT NOT NULL,
    DESCRIPTION    TEXT,
    USER_ID        TEXT,
    UPDATED_AT     TIMESTAMPTZ
);
