CREATE TABLE REFDATA.INDICATOR (
    INDICATOR_ID   INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME           TEXT NOT NULL UNIQUE,
    DISPLAY_NAME   TEXT NOT NULL,
    METHOD_NAME    TEXT NOT NULL,
    DESCRIPTION    TEXT,
    WIN_MIN        INTEGER,
    WIN_MAX        INTEGER,
    WIN_STEP       INTEGER,
    SIG_MIN        NUMERIC,
    SIG_MAX        NUMERIC,
    SIG_STEP       NUMERIC,
    IS_BOUNDED_IND CHAR(1),
    USER_ID        TEXT,
    UPDATED_AT     TIMESTAMPTZ
);
