CREATE TABLE REFDATA.PROMOTION_METRIC (
    PROMOTION_METRIC_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME                TEXT NOT NULL UNIQUE,
    DISPLAY_NAME        TEXT NOT NULL,
    METRIC_KEY          TEXT NOT NULL,
    DIRECTION           TEXT NOT NULL,
    REQUIREMENT_TYPE    TEXT NOT NULL,
    PRIORITY            INTEGER NOT NULL,
    THRESHOLD           NUMERIC,
    DESCRIPTION         TEXT,
    USER_ID             TEXT,
    UPDATED_AT          TIMESTAMPTZ
);
