CREATE TABLE REFDATA.PROMOTION_STATE (
    PROMOTION_STATE_ID  INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME                TEXT NOT NULL UNIQUE,
    DISPLAY_NAME        TEXT,
    DESCRIPTION         TEXT,
    USER_ID             TEXT,
    UPDATED_AT          TIMESTAMPTZ
);
