CREATE TABLE REFDATA.QUEUE_STATUS (
    QUEUE_STATUS_ID  INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME             TEXT NOT NULL,
    DISPLAY_NAME     TEXT,
    DESCRIPTION      TEXT,
    USER_ID          TEXT,
    UPDATED_AT       TIMESTAMPTZ
);
