CREATE TABLE REFDATA.SIGNAL_TYPE (
    SIGNAL_TYPE_ID  INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME            TEXT NOT NULL UNIQUE,
    DISPLAY_NAME    TEXT NOT NULL,
    FUNC_NAME_BAND    TEXT NOT NULL,
    FUNC_NAME_BOUNDED TEXT,
    DESCRIPTION     TEXT,
    USER_ID         TEXT,
    UPDATED_AT      TIMESTAMPTZ
);
