CREATE TABLE REFDATA.TICKER_MAPPING (
    TICKER_MAPPING_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DATA_TICKER       TEXT NOT NULL,
    BROKER            TEXT NOT NULL,
    BROKER_TICKER     TEXT NOT NULL,
    MARKET            TEXT,
    USER_ID           TEXT,
    CREATED_AT        TIMESTAMPTZ,
    UNIQUE (DATA_TICKER, BROKER)
);
