CREATE TABLE REFDATA.TM_INTERVAL (
    TM_INTERVAL_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME           TEXT NOT NULL,
    DISPLAY_NAME   TEXT NOT NULL,
    DESCRIPTION    TEXT,
    PERIOD_LENGTH  INTERVAL NOT NULL,
    USER_ID        TEXT,
    UPDATED_AT     TIMESTAMPTZ
);
