CREATE TABLE BT.STRATEGY (
    STRATEGY_ID    UUID PRIMARY KEY,
    NAME           TEXT NOT NULL,
    VERSION        INTEGER,
    TICKER         TEXT NOT NULL,
    CONJUNCTION    TEXT,
    TRADING_PERIOD INTEGER NOT NULL,
    CONFIG_JSON    JSONB NOT NULL,
    USER_ID        TEXT,
    CREATED_AT     TIMESTAMPTZ,
    UPDATED_AT     TIMESTAMPTZ,
    IS_CURRENT_IND CHAR(1)
);
