CREATE TABLE BT.STRATEGY (
    STRATEGY_ID      UUID NOT NULL,
    STRATEGY_VID     INTEGER NOT NULL,
    STRATEGY_NM      TEXT,
    CONFIG_JSON      JSONB NOT NULL,
    USER_ID          TEXT NOT NULL,
    CREATED_AT       TIMESTAMPTZ NOT NULL,
    TRANSACT_FROM_TS TIMESTAMPTZ NOT NULL,
    TRANSACT_TO_TS   TIMESTAMPTZ NOT NULL,  -- 9999-12-31 when active
    PRIMARY KEY (STRATEGY_ID, STRATEGY_VID)
);
