CREATE TABLE BT.STRATEGY (
    STRATEGY_ID      UUID NOT NULL,
    STRATEGY_VID     INTEGER NOT NULL,
    STRATEGY_NM      TEXT,
    CONFIG_JSON      JSONB NOT NULL,
    USER_ID          TEXT NOT NULL,
    CREATED_AT       TIMESTAMPTZ NOT NULL,
    TRANSACT_FROM_TS TIMESTAMPTZ NOT NULL,
    TRANSACT_TO_TS   TIMESTAMPTZ NOT NULL,  -- 9999-12-31 when active
    IS_BEST_IND      CHAR(1) NOT NULL,
    PRIMARY KEY (STRATEGY_ID, STRATEGY_VID),
    CONSTRAINT UQ_STRATEGY_USER_NM_VID UNIQUE (USER_ID, STRATEGY_NM, STRATEGY_VID)
);
