CREATE TABLE CORE_ADMIN.API_CREDENTIAL (
    API_CREDENTIAL_ID        INTEGER NOT NULL,
    API_CREDENTIAL_VID       INTEGER NOT NULL,
    APP_USER_ID              UUID NOT NULL,
    APP_ID                   INTEGER NOT NULL,
    LABEL                    TEXT NOT NULL,
    API_KEY_CIPHERTEXT       TEXT NOT NULL,
    API_SECRET_CIPHERTEXT    TEXT NOT NULL,
    IS_ACTIVE_IND            CHAR(1) NOT NULL,
    IS_CURRENT_IND           CHAR(1) NOT NULL,
    CREATED_AT               TIMESTAMPTZ NOT NULL,

    PRIMARY KEY (API_CREDENTIAL_ID, API_CREDENTIAL_VID)
);

CREATE INDEX IX_API_CREDENTIAL_USER_CURRENT
    ON CORE_ADMIN.API_CREDENTIAL (APP_USER_ID, IS_CURRENT_IND, IS_ACTIVE_IND);

-- quant_app: no direct table access (reads/writes via SPs only).
GRANT SELECT ON CORE_ADMIN.API_CREDENTIAL TO quant_admin;
