CREATE TABLE CORE_ADMIN.APP_USER (
    APP_USER_ID    UUID PRIMARY KEY,
    USERNAME       TEXT NOT NULL,
    PASSWORD_HASH  TEXT NOT NULL,
    IS_ACTIVE_IND  CHAR(1) NOT NULL,
    SESSION_GEN    INTEGER NOT NULL,
    LAST_LOGIN_AT  TIMESTAMPTZ,
    CREATED_AT     TIMESTAMPTZ,
    UPDATED_AT     TIMESTAMPTZ
);

CREATE UNIQUE INDEX UX_APP_USER_USERNAME
    ON CORE_ADMIN.APP_USER (USERNAME);
