CREATE TABLE CORE_ADMIN.LOG_PROC_SUMMARY (
    SUMMARY_DT       DATE             NOT NULL,
    SCHEMA_NM        TEXT             NOT NULL,
    PROC_NM          TEXT             NOT NULL,
    CALL_COUNT       INTEGER          NOT NULL,
    AVG_DURATION_MS  DOUBLE PRECISION,
    MAX_DURATION_MS  DOUBLE PRECISION,
    MIN_DURATION_MS  DOUBLE PRECISION,
    CREATED_AT       TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
    USER_ID          TEXT             NOT NULL DEFAULT 'system',
    PRIMARY KEY (SUMMARY_DT, SCHEMA_NM, PROC_NM)
);
